
## Use: nmake -f makefile.msc install

# Nothing much configurable below

TOPDIR = .\..\..
srcdir = $(TOPDIR)\..\sql\include
!INCLUDE $(TOPDIR)\..\NT\rules.msc
all: all-msc
check: check-msc
install: install-msc
INCLUDES = -I$(srcdir)
all-msc:
check-msc: all-msc
install-msc: install-exec install-data
install-exec:  
install-data:
